plugins:
  - serverless-offline
  - serverless-finch
service: my-homepage
region: eu-west-2
stage: ${opt:stage}
provider:
  name: aws
  environment:
    DYNAMO_TABLE: ${self:service}-storage
    APP_SECRET: ${ssm:/${self:service}-api/APP_SECRET}
    REACT_APP_API_URL: https://6lac5t2w1i.execute-api.eu-west-2.amazonaws.com/production/query
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
package:
  exclude:
    - ui/**
    - api/node_modules/serverless-dynamodb-client/**
    - api/node_modules/serverless-offline/**
functions:
  recipesAPI:
    name: ${self:service}-recipesAPI
    handler: api/handler.query
    cors: true
    events:
      - http:
          path: query 
          method: ANY
resources:
  Resources:
    MyStuffTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: Category
            AttributeType: S
          - AttributeName: Name
            AttributeType: S
        KeySchema:
          - AttributeName: Category
            KeyType: HASH
          - AttributeName: Name
            KeyType: RANGE
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMO_TABLE}
    uiBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "emma-corbett.me.uk"
custom:
  client:
    bucketName: "emma-corbett.me.uk"
    distributionFolder: ui/build
    indexDocument: index.html
    errorDocument: index.html