version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-cli: circleci/aws-cli@1.0
  serverless: circleci/serverless-framework@1.0
 
commands:
  configure-aws-account:
    description: "Configure AWS account credentials"
    steps:
      - run:
          command: aws configure set aws_access_key_id $AWS-ACCESS-KEY-ID --profile personal
          name: Configure AWS Access Key ID
      - run:
          command: aws configure set aws_secret_access_key $AWS-SECRET-ACCESS-KEY --profile personal
          name: Configure AWS Secret Access Key
jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup
      - configure-aws-account
      - run:
          name: Deploy UI & API
          command: make deploy

workflows:
  deploy-production:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
